namespace PlayGuide
{
    [default_interface]
    runtimeclass OptionItem
    {
        OptionItem(String text, Int32 _value);
        OptionItem(String text, Int32 _value, String description, String icon);
        String Text{ get; set; };
        String Description{ get; set; };
        Int32  Value{ get; set; };
        String Icon{ get; set; };
    }
}