import "AppSettingsViewModel.idl";

namespace PlayGuide
{
    [default_interface]
    runtimeclass SettingsPage : Microsoft.UI.Xaml.Controls.Page
    {
        SettingsPage();
        AppSettingsViewModel ViewModel{ get; };
    }
}
